USE [$(DatabaseName)]
GO

PRINT '------插入省份和地区数据------'

INSERT [Province] ([id],[ObjectName]) VALUES ( 1,'北京市')
INSERT [Province] ([id],[ObjectName]) VALUES ( 2,'天津市')
INSERT [Province] ([id],[ObjectName]) VALUES ( 3,'河北省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 4,'山西省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 5,'内蒙古自治区')
INSERT [Province] ([id],[ObjectName]) VALUES ( 6,'辽宁省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 7,'吉林省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 8,'黑龙江省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 9,'上海市')
INSERT [Province] ([id],[ObjectName]) VALUES ( 10,'江苏省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 11,'浙江省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 12,'安徽省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 13,'福建省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 14,'江西省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 15,'山东省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 16,'河南省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 17,'湖北省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 18,'湖南省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 19,'广东省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 20,'广西壮族自治区')
INSERT [Province] ([id],[ObjectName]) VALUES ( 21,'海南省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 22,'重庆市')
INSERT [Province] ([id],[ObjectName]) VALUES ( 23,'四川省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 24,'贵州省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 25,'云南省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 26,'西藏自治区')
INSERT [Province] ([id],[ObjectName]) VALUES ( 27,'陕西省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 28,'甘肃省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 29,'青海省')
INSERT [Province] ([id],[ObjectName]) VALUES ( 30,'宁夏回族自治区')
INSERT [Province] ([id],[ObjectName]) VALUES ( 31,'新疆维吾尔自治区')



INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(1,1,'市辖区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(2,2,'市辖区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(3,3,'石家庄市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(4,3,'唐山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(5,3,'秦皇岛市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(6,3,'邯郸市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(7,3,'邢台市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(8,3,'保定市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(9,3,'张家口市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(10,3,'承德市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(11,3,'沧州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(12,3,'廊坊市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(13,3,'衡水市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(14,4,'太原市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(15,4,'大同市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(16,4,'阳泉市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(17,4,'长治市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(18,4,'晋城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(19,4,'朔州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(20,4,'晋中市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(21,4,'运城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(22,4,'忻州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(23,4,'临汾市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(24,4,'吕梁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(25,5,'呼和浩特市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(26,5,'包头市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(27,5,'乌海市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(28,5,'赤峰市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(29,5,'通辽市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(30,5,'鄂尔多斯市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(31,5,'呼伦贝尔市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(32,5,'巴彦淖尔市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(33,5,'乌兰察布市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(34,5,'兴安盟')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(35,5,'锡林郭勒盟')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(36,5,'阿拉善盟')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(37,6,'沈阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(38,6,'大连市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(39,6,'鞍山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(40,6,'抚顺市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(41,6,'本溪市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(42,6,'丹东市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(43,6,'锦州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(44,6,'营口市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(45,6,'阜新市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(46,6,'辽阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(47,6,'盘锦市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(48,6,'铁岭市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(49,6,'朝阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(50,6,'葫芦岛市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(51,7,'长春市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(52,7,'吉林市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(53,7,'四平市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(54,7,'辽源市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(55,7,'通化市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(56,7,'白山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(57,7,'松原市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(58,7,'白城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(59,7,'延边朝鲜族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(60,8,'哈尔滨市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(61,8,'齐齐哈尔市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(62,8,'鸡西市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(63,8,'鹤岗市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(64,8,'双鸭山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(65,8,'大庆市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(66,8,'伊春市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(67,8,'佳木斯市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(68,8,'七台河市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(69,8,'牡丹江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(70,8,'黑河市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(71,8,'绥化市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(72,8,'大兴安岭地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(73,9,'市辖区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(74,10,'南京市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(75,10,'无锡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(76,10,'徐州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(77,10,'常州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(78,10,'苏州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(79,10,'南通市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(80,10,'连云港市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(81,10,'淮安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(82,10,'盐城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(83,10,'扬州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(84,10,'镇江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(85,10,'泰州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(86,10,'宿迁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(87,11,'杭州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(88,11,'宁波市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(89,11,'温州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(90,11,'嘉兴市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(91,11,'湖州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(92,11,'绍兴市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(93,11,'金华市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(94,11,'衢州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(95,11,'舟山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(96,11,'台州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(97,11,'丽水市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(98,12,'合肥市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(99,12,'芜湖市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(100,12,'蚌埠市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(101,12,'淮南市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(102,12,'马鞍山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(103,12,'淮北市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(104,12,'铜陵市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(105,12,'安庆市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(106,12,'黄山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(107,12,'滁州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(108,12,'阜阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(109,12,'宿州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(110,12,'巢湖市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(111,12,'六安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(112,12,'亳州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(113,12,'池州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(114,12,'宣城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(115,13,'福州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(116,13,'厦门市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(117,13,'莆田市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(118,13,'三明市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(119,13,'泉州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(120,13,'漳州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(121,13,'南平市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(122,13,'龙岩市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(123,13,'宁德市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(124,14,'南昌市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(125,14,'景德镇市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(126,14,'萍乡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(127,14,'九江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(128,14,'新余市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(129,14,'鹰潭市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(130,14,'赣州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(131,14,'吉安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(132,14,'宜春市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(133,14,'抚州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(134,14,'上饶市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(135,15,'济南市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(136,15,'青岛市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(137,15,'淄博市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(138,15,'枣庄市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(139,15,'东营市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(140,15,'烟台市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(141,15,'潍坊市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(142,15,'济宁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(143,15,'泰安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(144,15,'威海市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(145,15,'日照市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(146,15,'莱芜市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(147,15,'临沂市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(148,15,'德州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(149,15,'聊城市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(150,15,'滨州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(151,15,'荷泽市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(152,16,'郑州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(153,16,'开封市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(154,16,'洛阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(155,16,'平顶山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(156,16,'安阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(157,16,'鹤壁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(158,16,'新乡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(159,16,'焦作市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(160,16,'濮阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(161,16,'许昌市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(162,16,'漯河市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(163,16,'三门峡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(164,16,'南阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(165,16,'商丘市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(166,16,'信阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(167,16,'周口市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(168,16,'驻马店市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(169,17,'武汉市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(170,17,'黄石市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(171,17,'十堰市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(172,17,'宜昌市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(173,17,'襄樊市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(174,17,'鄂州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(175,17,'荆门市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(176,17,'孝感市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(177,17,'荆州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(178,17,'黄冈市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(179,17,'咸宁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(180,17,'随州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(181,17,'恩施土家族苗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(182,17,'省直辖行政单位')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(183,18,'长沙市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(184,18,'株洲市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(185,18,'湘潭市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(186,18,'衡阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(187,18,'邵阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(188,18,'岳阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(189,18,'常德市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(190,18,'张家界市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(191,18,'益阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(192,18,'郴州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(193,18,'永州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(194,18,'怀化市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(195,18,'娄底市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(196,18,'湘西土家族苗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(197,19,'广州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(198,19,'韶关市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(199,19,'深圳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(200,19,'珠海市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(201,19,'汕头市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(202,19,'佛山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(203,19,'江门市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(204,19,'湛江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(205,19,'茂名市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(206,19,'肇庆市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(207,19,'惠州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(208,19,'梅州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(209,19,'汕尾市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(210,19,'河源市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(211,19,'阳江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(212,19,'清远市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(213,19,'东莞市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(214,19,'中山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(215,19,'潮州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(216,19,'揭阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(217,19,'云浮市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(218,20,'南宁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(219,20,'柳州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(220,20,'桂林市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(221,20,'梧州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(222,20,'北海市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(223,20,'防城港市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(224,20,'钦州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(225,20,'贵港市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(226,20,'玉林市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(227,20,'百色市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(228,20,'贺州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(229,20,'河池市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(230,20,'来宾市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(231,20,'崇左市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(232,21,'海口市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(233,21,'三亚市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(234,21,'省直辖县级行政单位')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(235,22,'市辖区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(236,22,'市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(237,23,'成都市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(238,23,'自贡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(239,23,'攀枝花市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(240,23,'泸州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(241,23,'德阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(242,23,'绵阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(243,23,'广元市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(244,23,'遂宁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(245,23,'内江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(246,23,'乐山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(247,23,'南充市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(248,23,'眉山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(249,23,'宜宾市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(250,23,'广安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(251,23,'达州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(252,23,'雅安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(253,23,'巴中市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(254,23,'资阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(255,23,'阿坝藏族羌族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(256,23,'甘孜藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(257,23,'凉山彝族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(258,24,'贵阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(259,24,'六盘水市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(260,24,'遵义市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(261,24,'安顺市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(262,24,'铜仁地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(263,24,'黔西南布依族苗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(264,24,'毕节地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(265,24,'黔东南苗族侗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(266,24,'黔南布依族苗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(267,25,'昆明市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(268,25,'曲靖市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(269,25,'玉溪市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(270,25,'保山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(271,25,'昭通市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(272,25,'丽江市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(273,25,'思茅市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(274,25,'临沧市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(275,25,'楚雄彝族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(276,25,'红河哈尼族彝族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(277,25,'文山壮族苗族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(278,25,'西双版纳傣族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(279,25,'大理白族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(280,25,'德宏傣族景颇族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(281,25,'怒江傈僳族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(282,25,'迪庆藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(283,26,'拉萨市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(284,26,'昌都地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(285,26,'山南地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(286,26,'日喀则地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(287,26,'那曲地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(288,26,'阿里地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(289,26,'林芝地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(290,27,'西安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(291,27,'铜川市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(292,27,'宝鸡市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(293,27,'咸阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(294,27,'渭南市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(295,27,'延安市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(296,27,'汉中市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(297,27,'榆林市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(298,27,'安康市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(299,27,'商洛市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(300,28,'兰州市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(301,28,'嘉峪关市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(302,28,'金昌市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(303,28,'白银市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(304,28,'天水市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(305,28,'武威市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(306,28,'张掖市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(307,28,'平凉市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(308,28,'酒泉市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(309,28,'庆阳市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(310,28,'定西市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(311,28,'陇南市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(312,28,'临夏回族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(313,28,'甘南藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(314,29,'西宁市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(315,29,'海东地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(316,29,'海北藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(317,29,'黄南藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(318,29,'海南藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(319,29,'果洛藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(320,29,'玉树藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(321,29,'海西蒙古族藏族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(322,30,'银川市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(323,30,'石嘴山市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(324,30,'吴忠市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(325,30,'固原市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(326,30,'中卫市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(327,31,'乌鲁木齐市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(328,31,'克拉玛依市')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(329,31,'吐鲁番地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(330,31,'哈密地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(331,31,'昌吉回族自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(332,31,'博尔塔拉蒙古自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(333,31,'巴音郭楞蒙古自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(334,31,'阿克苏地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(335,31,'克孜勒苏柯尔克孜自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(336,31,'喀什地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(337,31,'和田地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(338,31,'伊犁哈萨克自治州')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(339,31,'塔城地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(340,31,'阿勒泰地区')
INSERT [Area] ([Id],[ProvinceId],[ObjectName]) VALUES(341,31,'省直辖行政单位')